export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#e5e2e1',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#594cc4',
        'secondary-fixed': '#c9e6ff',
        'surface-container': '#201f1f',
        'on-tertiary-container': '#003111',
        'surface': '#131313',
        'inverse-surface': '#e5e2e1',
        'primary-fixed-dim': '#c6bfff',
        'on-primary': '#290f95',
        'background': '#131313',
        'error': '#ffb4ab',
        'on-primary-fixed': '#160066',
        'on-secondary-fixed': '#001e2f',
        'outline-variant': '#474553',
        'on-surface-variant': '#c8c4d5',
        'surface-container-low': '#1c1b1b',
        'secondary-fixed-dim': '#89ceff',
        'on-primary-container': '#22008d',
        'secondary': '#89ceff',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed': '#002109',
        'tertiary-fixed': '#6bff8f',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-background': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-secondary-fixed-variant': '#004c6e',
        'surface-tint': '#c6bfff',
        'inverse-on-surface': '#313030',
        'tertiary': '#4ae176',
        'primary-fixed': '#e4dfff',
        'on-tertiary-fixed-variant': '#005321',
        'on-secondary': '#00344d',
        'primary': '#c6bfff',
        'on-primary-fixed-variant': '#4131ab',
        'surface-dim': '#131313',
        'on-tertiary': '#003915',
        'outline': '#928f9f',
        'error-container': '#93000a',
        'primary-container': '#8c81fb',
        'tertiary-container': '#00a74b',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-container': '#00344e',
        'secondary-container': '#00a2e6',
        'tertiary-fixed-dim': '#4ae176',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
